// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: operator/v1alpha1/operator.proto

// Configuration affecting Istio control plane installation version and shape.

package v1alpha1

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	v12 "k8s.io/api/apps/v1"
	v11 "k8s.io/api/autoscaling/v1"
	v1 "k8s.io/api/core/v1"
	v1beta1 "k8s.io/api/policy/v1beta1"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Status describes the current state of a component.
type InstallStatus_Status int32

const (
	// Component is not present.
	InstallStatus_NONE InstallStatus_Status = 0
	// Component is being updated to a different version.
	InstallStatus_UPDATING InstallStatus_Status = 1
	// Controller has started but not yet completed reconciliation loop for the component.
	InstallStatus_RECONCILING InstallStatus_Status = 2
	// Component is healthy.
	InstallStatus_HEALTHY InstallStatus_Status = 3
	// Component is in an error state.
	InstallStatus_ERROR InstallStatus_Status = 4
	// Overall status only and would not be set as a component status.
	// Action is needed from the user for reconciliation to proceed
	// e.g. There are proxies still pointing to the control plane revision when try to remove an `IstioOperator` CR.
	InstallStatus_ACTION_REQUIRED InstallStatus_Status = 5
)

var InstallStatus_Status_name = map[int32]string{
	0: "NONE",
	1: "UPDATING",
	2: "RECONCILING",
	3: "HEALTHY",
	4: "ERROR",
	5: "ACTION_REQUIRED",
}

var InstallStatus_Status_value = map[string]int32{
	"NONE":            0,
	"UPDATING":        1,
	"RECONCILING":     2,
	"HEALTHY":         3,
	"ERROR":           4,
	"ACTION_REQUIRED": 5,
}

func (x InstallStatus_Status) String() string {
	return proto.EnumName(InstallStatus_Status_name, int32(x))
}

func (InstallStatus_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8023ebf2dcfea843, []int{1, 0}
}

// IstioOperatorSpec defines the desired installed state of Istio components.
// The spec is a used to define a customization of the default profile values that are supplied with each Istio release.
// Because the spec is a customization API, specifying an empty IstioOperatorSpec results in a default Istio
// component values.
//
// ```yaml
// apiVersion: install.istio.io/v1alpha1
// kind: IstioOperator
// spec:
//   profile: default
//   hub: gcr.io/istio-testing
//   tag: latest
//   revision: 1-8-0
//   meshConfig:
//     accessLogFile: /dev/stdout
//     enableTracing: true
//   components:
//     egressGateways:
//     - name: istio-egressgateway
//       enabled: true
// ```
//
type IstioOperatorSpec struct {
	// Path or name for the profile e.g.
	//
	// * minimal (looks in profiles dir for a file called minimal.yaml)
	// * /tmp/istio/install/values/custom/custom-install.yaml (local file path)
	//
	// default profile is used if this field is unset.
	Profile string `protobuf:"bytes,10,opt,name=profile,proto3" json:"profile,omitempty"`
	// Path for the install package. e.g.
	//
	// * /tmp/istio-installer/nightly (local file path)
	//
	InstallPackagePath string `protobuf:"bytes,11,opt,name=install_package_path,json=installPackagePath,proto3" json:"installPackagePath,omitempty"`
	// Root for docker image paths e.g. `docker.io/istio`
	Hub string `protobuf:"bytes,12,opt,name=hub,proto3" json:"hub,omitempty"`
	// Version tag for docker images e.g. `1.7.2`
	Tag interface{} `protobuf:"bytes,13,opt,name=tag,proto3" json:"tag,omitempty"`
	// $hide_from_docs
	// Resource suffix is appended to all resources installed by each component.
	// Never implemented; replaced by revision.
	ResourceSuffix string `protobuf:"bytes,14,opt,name=resource_suffix,json=resourceSuffix,proto3" json:"resourceSuffix,omitempty"` // Deprecated: Do not use.
	// Namespace to install control plane resources into. If unset, Istio will be installed into the same namespace
	// as the `IstioOperator` CR. You must also set `values.global.istioNamespace` if you wish to install Istio in
	// a custom namespace.
	// If you have enabled CNI, you must  exclude this namespace by adding it to the list `values.cni.excludeNamespaces`.
	Namespace string `protobuf:"bytes,15,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Identify the revision this installation is associated with.
	// This option is currently experimental.
	Revision string `protobuf:"bytes,16,opt,name=revision,proto3" json:"revision,omitempty"`
	// Identify whether this revision is the default revision for the cluster
	// This option is currently experimental.
	DefaultRevision bool `protobuf:"varint,17,opt,name=default_revision,json=defaultRevision,proto3" json:"defaultRevision,omitempty"`
	// Config used by control plane components internally.
	MeshConfig map[string]interface{} `protobuf:"bytes,40,opt,name=mesh_config,json=meshConfig,proto3" json:"meshConfig,omitempty"`
	// Kubernetes resource settings, enablement and component-specific settings that are not internal to the
	// component.
	Components *IstioComponentSetSpec `protobuf:"bytes,50,opt,name=components,proto3" json:"components,omitempty"`
	// Deprecated.
	// Users should manage the installation of addon components on their own.
	// Refer to samples/addons for demo installation of addon components.
	AddonComponents map[string]*ExternalComponentSpec `protobuf:"bytes,51,rep,name=addon_components,json=addonComponents,proto3" json:"addonComponents,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // Deprecated: Do not use.
	// Overrides for default `values.yaml`. This is a validated pass-through to Helm templates.
	// See the [Helm installation options](https://istio.io/v1.5/docs/reference/config/installation-options/) for schema details.
	// Anything that is available in `IstioOperatorSpec` should be set above rather than using the passthrough. This
	// includes Kubernetes resource settings for components in `KubernetesResourcesSpec`.
	Values map[string]interface{} `protobuf:"bytes,100,opt,name=values,proto3" json:"values,omitempty"`
	// Unvalidated overrides for default `values.yaml`. Used for custom templates where new parameters are added.
	UnvalidatedValues    map[string]interface{} `protobuf:"bytes,101,opt,name=unvalidated_values,json=unvalidatedValues,proto3" json:"unvalidatedValues,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *IstioOperatorSpec) Reset()         { *m = IstioOperatorSpec{} }
func (m *IstioOperatorSpec) String() string { return proto.CompactTextString(m) }
func (*IstioOperatorSpec) ProtoMessage()    {}
func (*IstioOperatorSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_8023ebf2dcfea843, []int{0}
}
func (m *IstioOperatorSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IstioOperatorSpec.Unmarshal(m, b)
}
func (m *IstioOperatorSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IstioOperatorSpec.Marshal(b, m, deterministic)
}
func (m *IstioOperatorSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IstioOperatorSpec.Merge(m, src)
}
func (m *IstioOperatorSpec) XXX_Size() int {
	return xxx_messageInfo_IstioOperatorSpec.Size(m)
}
func (m *IstioOperatorSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_IstioOperatorSpec.DiscardUnknown(m)
}

var xxx_messageInfo_IstioOperatorSpec proto.InternalMessageInfo

func (m *IstioOperatorSpec) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

func (m *IstioOperatorSpec) GetInstallPackagePath() string {
	if m != nil {
		return m.InstallPackagePath
	}
	return ""
}

func (m *IstioOperatorSpec) GetHub() string {
	if m != nil {
		return m.Hub
	}
	return ""
}


// Deprecated: Do not use.
func (m *IstioOperatorSpec) GetResourceSuffix() string {
	if m != nil {
		return m.ResourceSuffix
	}
	return ""
}

func (m *IstioOperatorSpec) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *IstioOperatorSpec) GetRevision() string {
	if m != nil {
		return m.Revision
	}
	return ""
}

func (m *IstioOperatorSpec) GetDefaultRevision() bool {
	if m != nil {
		return m.DefaultRevision
	}
	return false
}


func (m *IstioOperatorSpec) GetComponents() *IstioComponentSetSpec {
	if m != nil {
		return m.Components
	}
	return nil
}

// Deprecated: Do not use.
func (m *IstioOperatorSpec) GetAddonComponents() map[string]*ExternalComponentSpec {
	if m != nil {
		return m.AddonComponents
	}
	return nil
}



// Observed state of IstioOperator
type InstallStatus struct {
	// Overall status of all components controlled by the operator.
	//
	// * If all components have status `NONE`, overall status is `NONE`.
	// * If all components are `HEALTHY`, overall status is `HEALTHY`.
	// * If one or more components are `RECONCILING` and others are `HEALTHY`, overall status is `RECONCILING`.
	// * If one or more components are `UPDATING` and others are `HEALTHY`, overall status is `UPDATING`.
	// * If components are a mix of `RECONCILING`, `UPDATING` and `HEALTHY`, overall status is `UPDATING`.
	// * If any component is in `ERROR` state, overall status is `ERROR`.
	// * If further action is needed for reconciliation to proceed, overall status is `ACTION_REQUIRED`.
	//
	Status InstallStatus_Status `protobuf:"varint,1,opt,name=status,proto3,enum=istio.operator.v1alpha1.InstallStatus_Status" json:"status,omitempty"`
	// Optional message providing additional information about the existing overall status.
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Individual status of each component controlled by the operator. The map key is the name of the component.
	ComponentStatus      map[string]*InstallStatus_VersionStatus `protobuf:"bytes,2,rep,name=component_status,json=componentStatus,proto3" json:"componentStatus,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *InstallStatus) Reset()         { *m = InstallStatus{} }
func (m *InstallStatus) String() string { return proto.CompactTextString(m) }
func (*InstallStatus) ProtoMessage()    {}
func (*InstallStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_8023ebf2dcfea843, []int{1}
}
func (m *InstallStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallStatus.Unmarshal(m, b)
}
func (m *InstallStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallStatus.Marshal(b, m, deterministic)
}
func (m *InstallStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallStatus.Merge(m, src)
}
func (m *InstallStatus) XXX_Size() int {
	return xxx_messageInfo_InstallStatus.Size(m)
}
func (m *InstallStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallStatus.DiscardUnknown(m)
}

var xxx_messageInfo_InstallStatus proto.InternalMessageInfo

func (m *InstallStatus) GetStatus() InstallStatus_Status {
	if m != nil {
		return m.Status
	}
	return InstallStatus_NONE
}

func (m *InstallStatus) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *InstallStatus) GetComponentStatus() map[string]*InstallStatus_VersionStatus {
	if m != nil {
		return m.ComponentStatus
	}
	return nil
}

// VersionStatus is the status and version of a component.
type InstallStatus_VersionStatus struct {
	Version              string               `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Status               InstallStatus_Status `protobuf:"varint,2,opt,name=status,proto3,enum=istio.operator.v1alpha1.InstallStatus_Status" json:"status,omitempty"`
	Error                string               `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *InstallStatus_VersionStatus) Reset()         { *m = InstallStatus_VersionStatus{} }
func (m *InstallStatus_VersionStatus) String() string { return proto.CompactTextString(m) }
func (*InstallStatus_VersionStatus) ProtoMessage()    {}
func (*InstallStatus_VersionStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_8023ebf2dcfea843, []int{1, 0}
}
func (m *InstallStatus_VersionStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallStatus_VersionStatus.Unmarshal(m, b)
}
func (m *InstallStatus_VersionStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallStatus_VersionStatus.Marshal(b, m, deterministic)
}
func (m *InstallStatus_VersionStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallStatus_VersionStatus.Merge(m, src)
}
func (m *InstallStatus_VersionStatus) XXX_Size() int {
	return xxx_messageInfo_InstallStatus_VersionStatus.Size(m)
}
func (m *InstallStatus_VersionStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallStatus_VersionStatus.DiscardUnknown(m)
}

var xxx_messageInfo_InstallStatus_VersionStatus proto.InternalMessageInfo

func (m *InstallStatus_VersionStatus) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *InstallStatus_VersionStatus) GetStatus() InstallStatus_Status {
	if m != nil {
		return m.Status
	}
	return InstallStatus_NONE
}

func (m *InstallStatus_VersionStatus) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

// IstioComponentSpec defines the desired installed state of Istio components.
type IstioComponentSetSpec struct {
	Base                 *BaseComponentSpec `protobuf:"bytes,29,opt,name=base,proto3" json:"base,omitempty"`
	Pilot                *ComponentSpec     `protobuf:"bytes,30,opt,name=pilot,proto3" json:"pilot,omitempty"`
	Cni                  *ComponentSpec     `protobuf:"bytes,38,opt,name=cni,proto3" json:"cni,omitempty"`
	IngressGateways      []*GatewaySpec     `protobuf:"bytes,40,rep,name=ingress_gateways,json=ingressGateways,proto3" json:"ingressGateways,omitempty"`
	EgressGateways       []*GatewaySpec     `protobuf:"bytes,41,rep,name=egress_gateways,json=egressGateways,proto3" json:"egressGateways,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *IstioComponentSetSpec) Reset()         { *m = IstioComponentSetSpec{} }
func (m *IstioComponentSetSpec) String() string { return proto.CompactTextString(m) }
func (*IstioComponentSetSpec) ProtoMessage()    {}
func (*IstioComponentSetSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_8023ebf2dcfea843, []int{2}
}
func (m *IstioComponentSetSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IstioComponentSetSpec.Unmarshal(m, b)
}
func (m *IstioComponentSetSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IstioComponentSetSpec.Marshal(b, m, deterministic)
}
func (m *IstioComponentSetSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IstioComponentSetSpec.Merge(m, src)
}
func (m *IstioComponentSetSpec) XXX_Size() int {
	return xxx_messageInfo_IstioComponentSetSpec.Size(m)
}
func (m *IstioComponentSetSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_IstioComponentSetSpec.DiscardUnknown(m)
}

var xxx_messageInfo_IstioComponentSetSpec proto.InternalMessageInfo

func (m *IstioComponentSetSpec) GetBase() *BaseComponentSpec {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *IstioComponentSetSpec) GetPilot() *ComponentSpec {
	if m != nil {
		return m.Pilot
	}
	return nil
}

func (m *IstioComponentSetSpec) GetCni() *ComponentSpec {
	if m != nil {
		return m.Cni
	}
	return nil
}

func (m *IstioComponentSetSpec) GetIngressGateways() []*GatewaySpec {
	if m != nil {
		return m.IngressGateways
	}
	return nil
}

func (m *IstioComponentSetSpec) GetEgressGateways() []*GatewaySpec {
	if m != nil {
		return m.EgressGateways
	}
	return nil
}

// Configuration for base component.
type BaseComponentSpec struct {
	// Selects whether this component is installed.
	Enabled *BoolValueForPB `protobuf:"bytes,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Kubernetes resource spec.
	K8S                  *KubernetesResourcesSpec `protobuf:"bytes,50,opt,name=k8s,proto3" json:"k8s,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *BaseComponentSpec) Reset()         { *m = BaseComponentSpec{} }
func (m *BaseComponentSpec) String() string { return proto.CompactTextString(m) }
func (*BaseComponentSpec) ProtoMessage()    {}
func (*BaseComponentSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_8023ebf2dcfea843, []int{3}
}
func (m *BaseComponentSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseComponentSpec.Unmarshal(m, b)
}
func (m *BaseComponentSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseComponentSpec.Marshal(b, m, deterministic)
}
func (m *BaseComponentSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseComponentSpec.Merge(m, src)
}
func (m *BaseComponentSpec) XXX_Size() int {
	return xxx_messageInfo_BaseComponentSpec.Size(m)
}
func (m *BaseComponentSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseComponentSpec.DiscardUnknown(m)
}

var xxx_messageInfo_BaseComponentSpec proto.InternalMessageInfo


func (m *BaseComponentSpec) GetK8S() *KubernetesResourcesSpec {
	if m != nil {
		return m.K8S
	}
	return nil
}

// Configuration for internal components.
type ComponentSpec struct {
	// Selects whether this component is installed.
	Enabled *BoolValueForPB `protobuf:"bytes,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Namespace for the component.
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Hub for the component (overrides top level hub setting).
	Hub string `protobuf:"bytes,10,opt,name=hub,proto3" json:"hub,omitempty"`
	// Tag for the component (overrides top level tag setting).
	Tag interface{} `protobuf:"bytes,11,opt,name=tag,proto3" json:"tag,omitempty"`
	// Arbitrary install time configuration for the component.
	Spec interface{} `protobuf:"bytes,30,opt,name=spec,proto3" json:"spec,omitempty"`
	// Kubernetes resource spec.
	K8S                  *KubernetesResourcesSpec `protobuf:"bytes,50,opt,name=k8s,proto3" json:"k8s,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ComponentSpec) Reset()         { *m = ComponentSpec{} }
func (m *ComponentSpec) String() string { return proto.CompactTextString(m) }
func (*ComponentSpec) ProtoMessage()    {}
func (*ComponentSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_8023ebf2dcfea843, []int{4}
}
func (m *ComponentSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComponentSpec.Unmarshal(m, b)
}
func (m *ComponentSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComponentSpec.Marshal(b, m, deterministic)
}
func (m *ComponentSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComponentSpec.Merge(m, src)
}
func (m *ComponentSpec) XXX_Size() int {
	return xxx_messageInfo_ComponentSpec.Size(m)
}
func (m *ComponentSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ComponentSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ComponentSpec proto.InternalMessageInfo


func (m *ComponentSpec) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ComponentSpec) GetHub() string {
	if m != nil {
		return m.Hub
	}
	return ""
}



func (m *ComponentSpec) GetK8S() *KubernetesResourcesSpec {
	if m != nil {
		return m.K8S
	}
	return nil
}

// Configuration for external components.
type ExternalComponentSpec struct {
	// Selects whether this component is installed.
	Enabled *BoolValueForPB `protobuf:"bytes,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Namespace for the component.
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Arbitrary install time configuration for the component.
	Spec interface{} `protobuf:"bytes,10,opt,name=spec,proto3" json:"spec,omitempty"`
	// Chart path for addon components.
	ChartPath string `protobuf:"bytes,30,opt,name=chart_path,json=chartPath,proto3" json:"chartPath,omitempty"`
	// Optional schema to validate spec against.
	Schema *types.Any `protobuf:"bytes,35,opt,name=schema,proto3" json:"schema,omitempty"`
	// Kubernetes resource spec.
	K8S                  *KubernetesResourcesSpec `protobuf:"bytes,50,opt,name=k8s,proto3" json:"k8s,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ExternalComponentSpec) Reset()         { *m = ExternalComponentSpec{} }
func (m *ExternalComponentSpec) String() string { return proto.CompactTextString(m) }
func (*ExternalComponentSpec) ProtoMessage()    {}
func (*ExternalComponentSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_8023ebf2dcfea843, []int{5}
}
func (m *ExternalComponentSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalComponentSpec.Unmarshal(m, b)
}
func (m *ExternalComponentSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalComponentSpec.Marshal(b, m, deterministic)
}
func (m *ExternalComponentSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalComponentSpec.Merge(m, src)
}
func (m *ExternalComponentSpec) XXX_Size() int {
	return xxx_messageInfo_ExternalComponentSpec.Size(m)
}
func (m *ExternalComponentSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalComponentSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalComponentSpec proto.InternalMessageInfo


func (m *ExternalComponentSpec) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}


func (m *ExternalComponentSpec) GetChartPath() string {
	if m != nil {
		return m.ChartPath
	}
	return ""
}

func (m *ExternalComponentSpec) GetSchema() *types.Any {
	if m != nil {
		return m.Schema
	}
	return nil
}

func (m *ExternalComponentSpec) GetK8S() *KubernetesResourcesSpec {
	if m != nil {
		return m.K8S
	}
	return nil
}

// Configuration for gateways.
type GatewaySpec struct {
	// Selects whether this gateway is installed.
	Enabled *BoolValueForPB `protobuf:"bytes,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Namespace for the gateway.
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Name for the gateway.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Labels for the gateway.
	Label map[string]string `protobuf:"bytes,4,rep,name=label,proto3" json:"label,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Hub for the component (overrides top level hub setting).
	Hub string `protobuf:"bytes,10,opt,name=hub,proto3" json:"hub,omitempty"`
	// Tag for the component (overrides top level tag setting).
	Tag interface{} `protobuf:"bytes,11,opt,name=tag,proto3" json:"tag,omitempty"`
	// Kubernetes resource spec.
	K8S                  *KubernetesResourcesSpec `protobuf:"bytes,50,opt,name=k8s,proto3" json:"k8s,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GatewaySpec) Reset()         { *m = GatewaySpec{} }
func (m *GatewaySpec) String() string { return proto.CompactTextString(m) }
func (*GatewaySpec) ProtoMessage()    {}
func (*GatewaySpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_8023ebf2dcfea843, []int{6}
}
func (m *GatewaySpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GatewaySpec.Unmarshal(m, b)
}
func (m *GatewaySpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GatewaySpec.Marshal(b, m, deterministic)
}
func (m *GatewaySpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GatewaySpec.Merge(m, src)
}
func (m *GatewaySpec) XXX_Size() int {
	return xxx_messageInfo_GatewaySpec.Size(m)
}
func (m *GatewaySpec) XXX_DiscardUnknown() {
	xxx_messageInfo_GatewaySpec.DiscardUnknown(m)
}

var xxx_messageInfo_GatewaySpec proto.InternalMessageInfo


func (m *GatewaySpec) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *GatewaySpec) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GatewaySpec) GetLabel() map[string]string {
	if m != nil {
		return m.Label
	}
	return nil
}

func (m *GatewaySpec) GetHub() string {
	if m != nil {
		return m.Hub
	}
	return ""
}


func (m *GatewaySpec) GetK8S() *KubernetesResourcesSpec {
	if m != nil {
		return m.K8S
	}
	return nil
}

// KubernetesResourcesConfig is a common set of k8s resource configs for components.
type KubernetesResourcesSpec struct {
	// k8s affinity.
	// [https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity)
	Affinity *v1.Affinity `protobuf:"bytes,1,opt,name=affinity,proto3" json:"affinity,omitempty"`
	// Deployment environment variables.
	// [https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/](https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/)
	Env []*v1.EnvVar `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty"`
	// k8s HorizontalPodAutoscaler settings.
	// [https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)
	HpaSpec *v11.HorizontalPodAutoscalerSpec `protobuf:"bytes,3,opt,name=hpa_spec,json=hpaSpec,proto3" json:"hpaSpec,omitempty"`
	// k8s imagePullPolicy.
	// [https://kubernetes.io/docs/concepts/containers/images/](https://kubernetes.io/docs/concepts/containers/images/)
	ImagePullPolicy string `protobuf:"bytes,4,opt,name=image_pull_policy,json=imagePullPolicy,proto3" json:"imagePullPolicy,omitempty"`
	// k8s nodeSelector.
	// [https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector)
	NodeSelector map[string]string `protobuf:"bytes,5,rep,name=node_selector,json=nodeSelector,proto3" json:"nodeSelector,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// k8s PodDisruptionBudget settings.
	// [https://kubernetes.io/docs/concepts/workloads/pods/disruptions/#how-disruption-budgets-work](https://kubernetes.io/docs/concepts/workloads/pods/disruptions/#how-disruption-budgets-work)
	PodDisruptionBudget *v1beta1.PodDisruptionBudgetSpec `protobuf:"bytes,6,opt,name=pod_disruption_budget,json=podDisruptionBudget,proto3" json:"podDisruptionBudget,omitempty"`
	// k8s pod annotations.
	// [https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/)
	PodAnnotations map[string]string `protobuf:"bytes,7,rep,name=pod_annotations,json=podAnnotations,proto3" json:"podAnnotations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// k8s priority_class_name. Default for all resources unless overridden.
	// [https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#priorityclass](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#priorityclass)
	PriorityClassName string `protobuf:"bytes,8,opt,name=priority_class_name,json=priorityClassName,proto3" json:"priorityClassName,omitempty"`
	// k8s readinessProbe settings.
	// [https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/)
	// k8s.io.api.core.v1.Probe readiness_probe = 9;
	ReadinessProbe *v1.Probe `protobuf:"bytes,9,opt,name=readiness_probe,json=readinessProbe,proto3" json:"readinessProbe,omitempty"`
	// k8s Deployment replicas setting.
	// [https://kubernetes.io/docs/concepts/workloads/controllers/deployment/](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/)
	ReplicaCount uint32 `protobuf:"varint,10,opt,name=replica_count,json=replicaCount,proto3" json:"replicaCount,omitempty"`
	// k8s resources settings.
	// [https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#resource-requests-and-limits-of-pod-and-container](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#resource-requests-and-limits-of-pod-and-container)
	Resources *v1.ResourceRequirements `protobuf:"bytes,11,opt,name=resources,proto3" json:"resources,omitempty"`
	// k8s Service settings.
	// [https://kubernetes.io/docs/concepts/services-networking/service/](https://kubernetes.io/docs/concepts/services-networking/service/)
	Service *v1.ServiceSpec `protobuf:"bytes,12,opt,name=service,proto3" json:"service,omitempty"`
	// k8s deployment strategy.
	// [https://kubernetes.io/docs/concepts/workloads/controllers/deployment/](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/)
	Strategy *v12.DeploymentStrategy `protobuf:"bytes,13,opt,name=strategy,proto3" json:"strategy,omitempty"`
	// k8s toleration
	// [https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/](https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/)
	Tolerations []*v1.Toleration `protobuf:"bytes,14,rep,name=tolerations,proto3" json:"tolerations,omitempty"`
	// k8s service annotations.
	// [https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/)
	ServiceAnnotations map[string]string `protobuf:"bytes,15,rep,name=service_annotations,json=serviceAnnotations,proto3" json:"serviceAnnotations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// k8s pod security context
	// [https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod)
	SecurityContext *v1.PodSecurityContext `protobuf:"bytes,16,opt,name=securityContext,proto3" json:"securityContext,omitempty"`
	// k8s volume
	// [https://kubernetes.io/docs/concepts/storage/volumes/](https://kubernetes.io/docs/concepts/storage/volumes/)
	// Volumes defines the collection of Volume to inject into the pod.
	Volumes []*v1.Volume `protobuf:"bytes,17,rep,name=volumes,proto3" json:"volumes,omitempty"`
	// k8s volumeMounts
	// VolumeMounts defines the collection of VolumeMount to inject into containers.
	VolumeMounts []*v1.VolumeMount `protobuf:"bytes,18,rep,name=volumeMounts,proto3" json:"volumeMounts,omitempty"`
	// Overlays for k8s resources in rendered manifests.
	Overlays             []*K8SObjectOverlay `protobuf:"bytes,100,rep,name=overlays,proto3" json:"overlays,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *KubernetesResourcesSpec) Reset()         { *m = KubernetesResourcesSpec{} }
func (m *KubernetesResourcesSpec) String() string { return proto.CompactTextString(m) }
func (*KubernetesResourcesSpec) ProtoMessage()    {}
func (*KubernetesResourcesSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_8023ebf2dcfea843, []int{7}
}
func (m *KubernetesResourcesSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KubernetesResourcesSpec.Unmarshal(m, b)
}
func (m *KubernetesResourcesSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KubernetesResourcesSpec.Marshal(b, m, deterministic)
}
func (m *KubernetesResourcesSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KubernetesResourcesSpec.Merge(m, src)
}
func (m *KubernetesResourcesSpec) XXX_Size() int {
	return xxx_messageInfo_KubernetesResourcesSpec.Size(m)
}
func (m *KubernetesResourcesSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_KubernetesResourcesSpec.DiscardUnknown(m)
}

var xxx_messageInfo_KubernetesResourcesSpec proto.InternalMessageInfo

func (m *KubernetesResourcesSpec) GetAffinity() *v1.Affinity {
	if m != nil {
		return m.Affinity
	}
	return nil
}

func (m *KubernetesResourcesSpec) GetEnv() []*v1.EnvVar {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *KubernetesResourcesSpec) GetHpaSpec() *v11.HorizontalPodAutoscalerSpec {
	if m != nil {
		return m.HpaSpec
	}
	return nil
}

func (m *KubernetesResourcesSpec) GetImagePullPolicy() string {
	if m != nil {
		return m.ImagePullPolicy
	}
	return ""
}

func (m *KubernetesResourcesSpec) GetNodeSelector() map[string]string {
	if m != nil {
		return m.NodeSelector
	}
	return nil
}

func (m *KubernetesResourcesSpec) GetPodDisruptionBudget() *v1beta1.PodDisruptionBudgetSpec {
	if m != nil {
		return m.PodDisruptionBudget
	}
	return nil
}

func (m *KubernetesResourcesSpec) GetPodAnnotations() map[string]string {
	if m != nil {
		return m.PodAnnotations
	}
	return nil
}

func (m *KubernetesResourcesSpec) GetPriorityClassName() string {
	if m != nil {
		return m.PriorityClassName
	}
	return ""
}

func (m *KubernetesResourcesSpec) GetReadinessProbe() *v1.Probe {
	if m != nil {
		return m.ReadinessProbe
	}
	return nil
}

func (m *KubernetesResourcesSpec) GetReplicaCount() uint32 {
	if m != nil {
		return m.ReplicaCount
	}
	return 0
}

func (m *KubernetesResourcesSpec) GetResources() *v1.ResourceRequirements {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *KubernetesResourcesSpec) GetService() *v1.ServiceSpec {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *KubernetesResourcesSpec) GetStrategy() *v12.DeploymentStrategy {
	if m != nil {
		return m.Strategy
	}
	return nil
}

func (m *KubernetesResourcesSpec) GetTolerations() []*v1.Toleration {
	if m != nil {
		return m.Tolerations
	}
	return nil
}

func (m *KubernetesResourcesSpec) GetServiceAnnotations() map[string]string {
	if m != nil {
		return m.ServiceAnnotations
	}
	return nil
}

func (m *KubernetesResourcesSpec) GetSecurityContext() *v1.PodSecurityContext {
	if m != nil {
		return m.SecurityContext
	}
	return nil
}

func (m *KubernetesResourcesSpec) GetVolumes() []*v1.Volume {
	if m != nil {
		return m.Volumes
	}
	return nil
}

func (m *KubernetesResourcesSpec) GetVolumeMounts() []*v1.VolumeMount {
	if m != nil {
		return m.VolumeMounts
	}
	return nil
}

func (m *KubernetesResourcesSpec) GetOverlays() []*K8SObjectOverlay {
	if m != nil {
		return m.Overlays
	}
	return nil
}

// Patch for an existing k8s resource.
type K8SObjectOverlay struct {
	// Resource API version.
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"apiVersion,omitempty"`
	// Resource kind.
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// Name of resource.
	// Namespace is always the component namespace.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// List of patches to apply to resource.
	Patches              []*K8SObjectOverlay_PathValue `protobuf:"bytes,4,rep,name=patches,proto3" json:"patches,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *K8SObjectOverlay) Reset()         { *m = K8SObjectOverlay{} }
func (m *K8SObjectOverlay) String() string { return proto.CompactTextString(m) }
func (*K8SObjectOverlay) ProtoMessage()    {}
func (*K8SObjectOverlay) Descriptor() ([]byte, []int) {
	return fileDescriptor_8023ebf2dcfea843, []int{8}
}
func (m *K8SObjectOverlay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_K8SObjectOverlay.Unmarshal(m, b)
}
func (m *K8SObjectOverlay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_K8SObjectOverlay.Marshal(b, m, deterministic)
}
func (m *K8SObjectOverlay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_K8SObjectOverlay.Merge(m, src)
}
func (m *K8SObjectOverlay) XXX_Size() int {
	return xxx_messageInfo_K8SObjectOverlay.Size(m)
}
func (m *K8SObjectOverlay) XXX_DiscardUnknown() {
	xxx_messageInfo_K8SObjectOverlay.DiscardUnknown(m)
}

var xxx_messageInfo_K8SObjectOverlay proto.InternalMessageInfo

func (m *K8SObjectOverlay) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

func (m *K8SObjectOverlay) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *K8SObjectOverlay) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *K8SObjectOverlay) GetPatches() []*K8SObjectOverlay_PathValue {
	if m != nil {
		return m.Patches
	}
	return nil
}

type K8SObjectOverlay_PathValue struct {
	// Path of the form a.[key1:value1].b.[:value2]
	// Where [key1:value1] is a selector for a key-value pair to identify a list element and [:value] is a value
	// selector to identify a list element in a leaf list.
	// All path intermediate nodes must exist.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Value to add, delete or replace.
	// For add, the path should be a new leaf.
	// For delete, value should be unset.
	// For replace, path should reference an existing node.
	// All values are strings but are converted into appropriate type based on schema.
	Value                interface{} `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *K8SObjectOverlay_PathValue) Reset()         { *m = K8SObjectOverlay_PathValue{} }
func (m *K8SObjectOverlay_PathValue) String() string { return proto.CompactTextString(m) }
func (*K8SObjectOverlay_PathValue) ProtoMessage()    {}
func (*K8SObjectOverlay_PathValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_8023ebf2dcfea843, []int{8, 0}
}
func (m *K8SObjectOverlay_PathValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_K8SObjectOverlay_PathValue.Unmarshal(m, b)
}
func (m *K8SObjectOverlay_PathValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_K8SObjectOverlay_PathValue.Marshal(b, m, deterministic)
}
func (m *K8SObjectOverlay_PathValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_K8SObjectOverlay_PathValue.Merge(m, src)
}
func (m *K8SObjectOverlay_PathValue) XXX_Size() int {
	return xxx_messageInfo_K8SObjectOverlay_PathValue.Size(m)
}
func (m *K8SObjectOverlay_PathValue) XXX_DiscardUnknown() {
	xxx_messageInfo_K8SObjectOverlay_PathValue.DiscardUnknown(m)
}

var xxx_messageInfo_K8SObjectOverlay_PathValue proto.InternalMessageInfo

func (m *K8SObjectOverlay_PathValue) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}


// Synthetic type for generating Go structs.

// Synthetic type for generating Go structs.

// Synthetic type for generating Go structs.

// Synthetic type for generating Go structs.

func init() {
	proto.RegisterEnum("istio.operator.v1alpha1.InstallStatus_Status", InstallStatus_Status_name, InstallStatus_Status_value)
	proto.RegisterType((*IstioOperatorSpec)(nil), "istio.operator.v1alpha1.IstioOperatorSpec")
	proto.RegisterMapType((map[string]*ExternalComponentSpec)(nil), "istio.operator.v1alpha1.IstioOperatorSpec.AddonComponentsEntry")
	proto.RegisterType((*InstallStatus)(nil), "istio.operator.v1alpha1.InstallStatus")
	proto.RegisterMapType((map[string]*InstallStatus_VersionStatus)(nil), "istio.operator.v1alpha1.InstallStatus.ComponentStatusEntry")
	proto.RegisterType((*InstallStatus_VersionStatus)(nil), "istio.operator.v1alpha1.InstallStatus.VersionStatus")
	proto.RegisterType((*IstioComponentSetSpec)(nil), "istio.operator.v1alpha1.IstioComponentSetSpec")
	proto.RegisterType((*BaseComponentSpec)(nil), "istio.operator.v1alpha1.BaseComponentSpec")
	proto.RegisterType((*ComponentSpec)(nil), "istio.operator.v1alpha1.ComponentSpec")
	proto.RegisterType((*ExternalComponentSpec)(nil), "istio.operator.v1alpha1.ExternalComponentSpec")
	proto.RegisterType((*GatewaySpec)(nil), "istio.operator.v1alpha1.GatewaySpec")
	proto.RegisterMapType((map[string]string)(nil), "istio.operator.v1alpha1.GatewaySpec.LabelEntry")
	proto.RegisterType((*KubernetesResourcesSpec)(nil), "istio.operator.v1alpha1.KubernetesResourcesSpec")
	proto.RegisterMapType((map[string]string)(nil), "istio.operator.v1alpha1.KubernetesResourcesSpec.NodeSelectorEntry")
	proto.RegisterMapType((map[string]string)(nil), "istio.operator.v1alpha1.KubernetesResourcesSpec.PodAnnotationsEntry")
	proto.RegisterMapType((map[string]string)(nil), "istio.operator.v1alpha1.KubernetesResourcesSpec.ServiceAnnotationsEntry")
	proto.RegisterType((*K8SObjectOverlay)(nil), "istio.operator.v1alpha1.K8sObjectOverlay")
	proto.RegisterType((*K8SObjectOverlay_PathValue)(nil), "istio.operator.v1alpha1.K8sObjectOverlay.PathValue")
}

func init() { proto.RegisterFile("operator/v1alpha1/operator.proto", fileDescriptor_8023ebf2dcfea843) }

var fileDescriptor_8023ebf2dcfea843 = []byte{
	// 1867 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0x51, 0x73, 0xdb, 0xc6,
	0x11, 0xb6, 0x48, 0x4a, 0xa2, 0x96, 0x92, 0x08, 0x9d, 0x94, 0x18, 0xe1, 0x24, 0xb2, 0x42, 0x3b,
	0xae, 0x9c, 0xb8, 0x60, 0x24, 0x67, 0x3a, 0x6a, 0xda, 0x69, 0x2a, 0x4a, 0x8c, 0x2d, 0xd5, 0x96,
	0x98, 0x93, 0xe2, 0x99, 0x76, 0xa6, 0xc1, 0x1c, 0x81, 0x25, 0x89, 0x0a, 0xc4, 0xa1, 0xb8, 0x03,
	0x2b, 0xf6, 0x07, 0x74, 0xa6, 0xbf, 0xa0, 0x6f, 0xfd, 0x23, 0xed, 0x43, 0x1f, 0xdb, 0xb7, 0xfe,
	0x84, 0x8e, 0x9f, 0xfb, 0xde, 0xd7, 0xce, 0x1d, 0x40, 0x0a, 0x94, 0x48, 0x5b, 0x74, 0xdd, 0x3c,
	0x11, 0xb7, 0xb7, 0xdf, 0x77, 0xb7, 0xb7, 0x7b, 0xb7, 0xbb, 0x84, 0x2d, 0x1e, 0x62, 0xc4, 0x24,
	0x8f, 0x6a, 0xfd, 0x1d, 0xe6, 0x87, 0x5d, 0xb6, 0x53, 0x1b, 0x4a, 0xac, 0x30, 0xe2, 0x92, 0x93,
	0xbb, 0x9e, 0x90, 0x1e, 0xb7, 0x46, 0xd2, 0xa1, 0x5e, 0xe5, 0x83, 0x0e, 0xe7, 0x1d, 0x1f, 0x6b,
	0x5a, 0xad, 0x15, 0xb7, 0x6b, 0x2c, 0x18, 0x24, 0x98, 0xca, 0xa3, 0x8b, 0x3d, 0x61, 0x79, 0xbc,
	0xc6, 0x42, 0xaf, 0xc6, 0x62, 0xc9, 0x85, 0xc3, 0x7c, 0x2f, 0xe8, 0xd4, 0xfa, 0x3b, 0xb5, 0x0e,
	0x06, 0x8a, 0x08, 0xdd, 0x09, 0xaa, 0x21, 0xf7, 0x3d, 0x67, 0x50, 0xeb, 0xef, 0xb4, 0x50, 0xb2,
	0x9b, 0xaa, 0xd5, 0x2c, 0x6b, 0x18, 0x8a, 0x49, 0x74, 0x59, 0x1d, 0x87, 0x47, 0x38, 0x49, 0x67,
	0xa3, 0xc3, 0x3b, 0x5c, 0x7f, 0xd6, 0xd4, 0x57, 0x22, 0xad, 0xfe, 0x7b, 0x01, 0xd6, 0x8e, 0x94,
	0xa9, 0xa7, 0xa9, 0xa5, 0x67, 0x21, 0x3a, 0xc4, 0x84, 0xc5, 0x30, 0xe2, 0x6d, 0xcf, 0x47, 0x13,
	0xb6, 0xe6, 0xb6, 0x97, 0xe8, 0x70, 0x48, 0x3e, 0x87, 0x0d, 0x2f, 0x10, 0x92, 0xf9, 0xbe, 0x1d,
	0x32, 0xe7, 0x82, 0x75, 0xd0, 0x0e, 0x99, 0xec, 0x9a, 0x25, 0xad, 0x46, 0xd2, 0xb9, 0x66, 0x32,
	0xd5, 0x64, 0xb2, 0x4b, 0x0c, 0xc8, 0x77, 0xe3, 0x96, 0xb9, 0xac, 0x15, 0xd4, 0x27, 0xd9, 0x83,
	0xbc, 0x64, 0x1d, 0x73, 0x65, 0x6b, 0x6e, 0xbb, 0xb4, 0xfb, 0xd0, 0x9a, 0x72, 0xd2, 0xd6, 0xf9,
	0x20, 0xc4, 0xa3, 0x40, 0x62, 0xd4, 0x66, 0x0e, 0x52, 0x05, 0x21, 0x9f, 0x41, 0x39, 0x42, 0xc1,
	0xe3, 0xc8, 0x41, 0x5b, 0xc4, 0xed, 0xb6, 0x77, 0x69, 0xae, 0x2a, 0xde, 0x7a, 0xce, 0x9c, 0xa3,
	0xab, 0xc3, 0xa9, 0x33, 0x3d, 0x43, 0x3e, 0x84, 0xa5, 0x80, 0xf5, 0x50, 0x84, 0xcc, 0x41, 0xb3,
	0xac, 0x97, 0xbf, 0x12, 0x90, 0x0a, 0x14, 0x23, 0xec, 0x7b, 0xc2, 0xe3, 0x81, 0x69, 0xe8, 0xc9,
	0xd1, 0x98, 0x3c, 0x02, 0xc3, 0xc5, 0x36, 0x8b, 0x7d, 0x69, 0x8f, 0x74, 0xd6, 0xb6, 0xe6, 0xb6,
	0x8b, 0xb4, 0x9c, 0xca, 0xe9, 0x50, 0xb5, 0x09, 0xa5, 0x1e, 0x8a, 0xae, 0xed, 0xf0, 0xa0, 0xed,
	0x75, 0xcc, 0x6d, 0x6d, 0x53, 0xed, 0xb5, 0x36, 0xbd, 0x60, 0xe1, 0x99, 0x8c, 0xbc, 0xa0, 0x73,
	0x65, 0x1c, 0x28, 0x8e, 0x03, 0x4d, 0x41, 0x4e, 0x00, 0x1c, 0xde, 0x0b, 0x79, 0x80, 0x81, 0x14,
	0xe6, 0xae, 0x26, 0xb4, 0xa6, 0x12, 0x6a, 0xdf, 0x1d, 0x0c, 0xf5, 0xcf, 0x50, 0x2a, 0xff, 0xd1,
	0x0c, 0x03, 0x09, 0xc0, 0x60, 0xae, 0xcb, 0x03, 0x3b, 0xc3, 0xfa, 0x64, 0x2b, 0xbf, 0x5d, 0xda,
	0xfd, 0xea, 0xf5, 0xac, 0xd9, 0x88, 0xb0, 0xf6, 0x15, 0xc5, 0x68, 0x1d, 0xd1, 0x08, 0x64, 0x34,
	0xd0, 0xa7, 0x5e, 0x66, 0xe3, 0x33, 0xe4, 0x29, 0x2c, 0xf4, 0x99, 0x1f, 0xa3, 0x30, 0xdd, 0xb7,
	0x3b, 0x8c, 0x14, 0x4e, 0xbe, 0x03, 0x12, 0x07, 0x7d, 0xe6, 0x7b, 0xae, 0x8a, 0x62, 0x3b, 0x25,
	0xc5, 0xb7, 0x23, 0x5d, 0xcb, 0x50, 0xbd, 0xd4, 0x4c, 0x95, 0x08, 0x36, 0x26, 0x59, 0xa5, 0x02,
	0xf6, 0x02, 0x07, 0xe6, 0x5c, 0x12, 0xb0, 0x17, 0x38, 0x20, 0x87, 0x30, 0xaf, 0x57, 0x37, 0x73,
	0x6f, 0xf0, 0x46, 0xe3, 0x52, 0x62, 0x14, 0x30, 0xff, 0xca, 0x21, 0xca, 0x1b, 0x09, 0xf8, 0xcb,
	0xdc, 0xde, 0x5c, 0xf5, 0x2f, 0x05, 0x58, 0x39, 0x4a, 0xee, 0xc8, 0x99, 0x64, 0x32, 0x16, 0xa4,
	0x01, 0x0b, 0x42, 0x7f, 0xe9, 0x05, 0x57, 0x77, 0x7f, 0x38, 0xdd, 0x29, 0x59, 0x9c, 0x95, 0xfc,
	0xd0, 0x14, 0xac, 0x6e, 0x6c, 0x0f, 0x85, 0x60, 0x1d, 0x34, 0xf3, 0xc9, 0x8d, 0x4d, 0x87, 0xa4,
	0x0d, 0xc6, 0xc8, 0xf3, 0x76, 0xba, 0x54, 0x4e, 0xfb, 0xff, 0x27, 0xb7, 0x5c, 0xea, 0xca, 0x1a,
	0x3d, 0xd6, 0xa7, 0x44, 0xcb, 0xce, 0xb8, 0xb4, 0xf2, 0x87, 0x39, 0x58, 0x79, 0x89, 0x91, 0xba,
	0x15, 0x67, 0xa3, 0x3d, 0xf5, 0x13, 0x41, 0x7a, 0x98, 0xc3, 0x61, 0xc6, 0xe8, 0xdc, 0xff, 0x62,
	0xf4, 0x06, 0xcc, 0x63, 0x14, 0xf1, 0xc8, 0x2c, 0x68, 0xfa, 0x64, 0x50, 0xb9, 0x84, 0x8d, 0x49,
	0x3b, 0x9e, 0xe0, 0xd7, 0xe3, 0x71, 0xbf, 0x7e, 0x71, 0xcb, 0x5d, 0x8c, 0x59, 0x99, 0xf5, 0xee,
	0x77, 0xb0, 0x90, 0x9a, 0x5e, 0x84, 0xc2, 0xc9, 0xe9, 0x49, 0xc3, 0xb8, 0x43, 0x96, 0xa1, 0xf8,
	0x6d, 0xf3, 0x70, 0xff, 0xfc, 0xe8, 0xe4, 0xa9, 0x31, 0x47, 0xca, 0x50, 0xa2, 0x8d, 0x83, 0xd3,
	0x93, 0x83, 0xa3, 0xe7, 0x4a, 0x90, 0x23, 0x25, 0x58, 0x7c, 0xd6, 0xd8, 0x7f, 0x7e, 0xfe, 0xec,
	0x97, 0x46, 0x9e, 0x2c, 0xc1, 0x7c, 0x83, 0xd2, 0x53, 0x6a, 0x14, 0xc8, 0x3a, 0x94, 0xf7, 0x0f,
	0xce, 0x8f, 0x4e, 0x4f, 0x6c, 0xda, 0xf8, 0xe6, 0xdb, 0x23, 0xda, 0x38, 0x34, 0xe6, 0xab, 0xff,
	0xc9, 0xc3, 0x7b, 0x13, 0x2f, 0x3c, 0xf9, 0x19, 0x14, 0x5a, 0x4c, 0xa0, 0xf9, 0x91, 0x36, 0xe4,
	0xd3, 0xa9, 0x86, 0xd4, 0x99, 0xc0, 0xf1, 0xe0, 0xd4, 0x38, 0xf2, 0x53, 0x98, 0x0f, 0x3d, 0x9f,
	0x4b, 0x73, 0xf3, 0x0d, 0x8f, 0xf2, 0xb5, 0xc8, 0xd6, 0x20, 0xf5, 0xa0, 0x3b, 0x81, 0x67, 0x3e,
	0x9c, 0x09, 0xab, 0x20, 0xe4, 0x14, 0x0c, 0x2f, 0xe8, 0x44, 0x28, 0x84, 0xdd, 0x61, 0x12, 0x7f,
	0xc7, 0x06, 0xc2, 0xdc, 0xd6, 0xc1, 0xf9, 0x60, 0x2a, 0xcd, 0xd3, 0x44, 0x51, 0x93, 0x94, 0x53,
	0x74, 0x2a, 0x13, 0xe4, 0x05, 0x94, 0xf1, 0x1a, 0xdf, 0xa3, 0x19, 0xf8, 0x56, 0x71, 0x8c, 0xee,
	0xb8, 0x50, 0xbc, 0x67, 0x6c, 0x1d, 0x17, 0x8a, 0x5b, 0xc6, 0xc7, 0xc7, 0x85, 0xe2, 0xc7, 0x46,
	0xf5, 0xb8, 0x50, 0xac, 0x1a, 0xf7, 0x8f, 0x0b, 0xc5, 0xfb, 0xc6, 0x83, 0xe3, 0x42, 0xf1, 0x81,
	0xf1, 0xc9, 0x71, 0xa1, 0xf8, 0x89, 0xf1, 0xf0, 0xb8, 0x50, 0xfc, 0x81, 0xb1, 0x4d, 0x17, 0x1d,
	0x4f, 0x32, 0x17, 0x7d, 0xba, 0x90, 0x64, 0x75, 0xba, 0x24, 0xd1, 0xc7, 0x1e, 0xaa, 0x1b, 0xb3,
	0xd0, 0x61, 0xbe, 0x8f, 0x03, 0x0a, 0x01, 0x77, 0xd1, 0x66, 0x1d, 0x0c, 0x24, 0x9d, 0x0f, 0x23,
	0x7e, 0x39, 0xa0, 0x86, 0xf0, 0x5c, 0x74, 0x58, 0x64, 0x7b, 0xc1, 0x6f, 0xd0, 0x91, 0x3c, 0xa2,
	0x2b, 0x7a, 0xb7, 0xae, 0x1d, 0x61, 0x8f, 0x4b, 0xac, 0xfe, 0x79, 0x0e, 0xd6, 0x6e, 0xf8, 0x8e,
	0x34, 0x60, 0x11, 0x03, 0xd6, 0xf2, 0xd1, 0xd5, 0x51, 0x5d, 0xda, 0xfd, 0xec, 0xb5, 0xcf, 0x62,
	0x9d, 0x73, 0x5f, 0xbf, 0x7d, 0x5f, 0xf3, 0xa8, 0x59, 0xa7, 0x43, 0x2c, 0xa9, 0x43, 0xfe, 0x62,
	0x6f, 0x98, 0x6a, 0x3e, 0x9f, 0x4a, 0xf1, 0x8b, 0xb8, 0x85, 0x51, 0x80, 0x12, 0x05, 0x4d, 0x13,
	0xad, 0x48, 0x1c, 0x79, 0xb1, 0x27, 0xaa, 0x7f, 0xcb, 0xc1, 0xca, 0xff, 0x65, 0x73, 0x63, 0x59,
	0x3c, 0x77, 0x3d, 0x8b, 0xa7, 0xc5, 0x05, 0xdc, 0x28, 0x2e, 0x4a, 0xb3, 0x17, 0x17, 0x5f, 0x42,
	0x41, 0x84, 0xe8, 0xbc, 0xf1, 0x0a, 0x8c, 0x43, 0x35, 0xe6, 0x9d, 0x1c, 0xe1, 0x3f, 0x72, 0xf0,
	0xde, 0xc4, 0x04, 0xf2, 0xfd, 0x1c, 0xe5, 0xd0, 0x7c, 0x78, 0x0b, 0xf3, 0x3f, 0x02, 0x70, 0xba,
	0x2c, 0x92, 0x49, 0x2d, 0xb8, 0x99, 0x50, 0x6b, 0x89, 0x2e, 0x01, 0x1f, 0xc3, 0x82, 0x70, 0xba,
	0xd8, 0x63, 0xe6, 0x7d, 0x4d, 0xbe, 0x61, 0x25, 0x45, 0xb4, 0x35, 0x2c, 0xa2, 0xad, 0xfd, 0x60,
	0x40, 0x53, 0x9d, 0x77, 0x72, 0x96, 0x7f, 0xca, 0x43, 0x29, 0x73, 0xaf, 0xbf, 0x9f, 0x13, 0x24,
	0x50, 0x50, 0x83, 0x34, 0x01, 0xeb, 0x6f, 0xd2, 0x80, 0x79, 0x9f, 0xb5, 0xd0, 0x37, 0x0b, 0xfa,
	0x15, 0xaa, 0xdd, 0xe6, 0x15, 0xb2, 0x9e, 0x2b, 0x44, 0x92, 0x66, 0x13, 0xf4, 0x3b, 0x8d, 0xf3,
	0x77, 0x70, 0xbe, 0x95, 0x3d, 0x80, 0xab, 0x4d, 0x4e, 0xc8, 0xac, 0x1b, 0xd9, 0xcc, 0xba, 0x94,
	0xcd, 0x91, 0x7f, 0x5d, 0x86, 0xbb, 0x53, 0xa8, 0xc9, 0x1e, 0x14, 0x59, 0xbb, 0xed, 0x05, 0x9e,
	0x1c, 0xa4, 0x6e, 0xfa, 0xd0, 0x4a, 0x3a, 0x1b, 0x8b, 0x85, 0x9e, 0xa5, 0x3a, 0x1b, 0xab, 0xbf,
	0x63, 0xed, 0xa7, 0x3a, 0x74, 0xa4, 0x4d, 0x1e, 0x43, 0x1e, 0x83, 0x7e, 0x5a, 0xd7, 0x54, 0x26,
	0x81, 0x1a, 0x41, 0xff, 0x25, 0x8b, 0xa8, 0x52, 0x23, 0xdf, 0x40, 0xb1, 0x1b, 0x32, 0x5b, 0x87,
	0x7b, 0x5e, 0xaf, 0xf3, 0xa3, 0x2c, 0x24, 0xd3, 0xbb, 0x29, 0xe4, 0x33, 0x1e, 0x79, 0xbf, 0xe7,
	0x81, 0x64, 0x7e, 0x93, 0xbb, 0xfb, 0xe9, 0x1c, 0xea, 0xb2, 0x98, 0x2e, 0x76, 0x43, 0xa6, 0xb7,
	0xfe, 0x29, 0xac, 0x79, 0x3d, 0xdd, 0x0d, 0xc5, 0xaa, 0x35, 0xd2, 0x8f, 0x7f, 0x5a, 0x96, 0x94,
	0xf5, 0x44, 0x33, 0xf6, 0xfd, 0xa6, 0x16, 0x93, 0x0e, 0xac, 0xe8, 0x14, 0x20, 0xd0, 0xd7, 0x8f,
	0xbd, 0x39, 0xaf, 0xb7, 0x5d, 0x9f, 0xd5, 0x15, 0xd6, 0x09, 0x77, 0xf1, 0x2c, 0x25, 0x49, 0xc2,
	0x65, 0x39, 0xc8, 0x88, 0x48, 0x1b, 0xde, 0x0b, 0xb9, 0x6b, 0xbb, 0x9e, 0x88, 0xe2, 0x50, 0x7a,
	0x3c, 0xb0, 0x5b, 0xb1, 0xdb, 0x41, 0x69, 0x2e, 0x68, 0xa3, 0x77, 0xb3, 0x46, 0x27, 0x5b, 0xb6,
	0xd2, 0x2e, 0xd4, 0x6a, 0x72, 0xf7, 0x70, 0x04, 0xab, 0x6b, 0x94, 0x36, 0x78, 0x3d, 0xbc, 0x39,
	0x41, 0x7a, 0x50, 0x56, 0xeb, 0xb0, 0x20, 0xe0, 0x92, 0x29, 0xb9, 0x30, 0x17, 0xb5, 0x49, 0x87,
	0x33, 0x9b, 0xa4, 0x8e, 0xf8, 0x8a, 0x26, 0x31, 0x6a, 0x35, 0x1c, 0x13, 0x12, 0x0b, 0xd6, 0xc3,
	0xc8, 0xe3, 0x91, 0x27, 0x07, 0xb6, 0xe3, 0x33, 0x21, 0x6c, 0x7d, 0xed, 0x8a, 0xfa, 0xb4, 0xd7,
	0x86, 0x53, 0x07, 0x6a, 0xe6, 0x44, 0xdd, 0xc1, 0xba, 0xea, 0x1a, 0x99, 0xeb, 0x05, 0xaa, 0x2c,
	0x08, 0x23, 0xde, 0x42, 0x73, 0x49, 0x1f, 0xc0, 0x07, 0x93, 0x02, 0xa5, 0xa9, 0x14, 0x54, 0x33,
	0x99, 0x22, 0xf4, 0x98, 0xdc, 0x87, 0x95, 0x08, 0x43, 0xdf, 0x73, 0x98, 0xed, 0xf0, 0x38, 0x90,
	0xfa, 0x2a, 0xae, 0xd0, 0xe5, 0x54, 0x78, 0xa0, 0x64, 0xe4, 0x6b, 0x58, 0x1a, 0xf6, 0xa0, 0x22,
	0xbd, 0x99, 0xdb, 0x93, 0x96, 0x18, 0x9a, 0x4c, 0xf1, 0xb7, 0xb1, 0x17, 0x61, 0x4f, 0xf5, 0x1e,
	0xf4, 0x0a, 0x4a, 0x7e, 0x0c, 0x8b, 0x02, 0xa3, 0xbe, 0xe7, 0xa0, 0x6e, 0x9b, 0x4b, 0xbb, 0xf7,
	0x26, 0xb1, 0x9c, 0x25, 0x2a, 0x49, 0x1c, 0xa6, 0xfa, 0xa4, 0x0e, 0x45, 0x21, 0x55, 0xdb, 0xdf,
	0x19, 0x8c, 0x1a, 0xec, 0x6c, 0x68, 0x87, 0xa1, 0x50, 0xd8, 0x43, 0x0c, 0x7d, 0x3e, 0xe8, 0xe9,
	0x0a, 0x39, 0xd1, 0xa6, 0x23, 0x1c, 0xf9, 0x39, 0x94, 0x24, 0xf7, 0x95, 0xc7, 0xb4, 0x2b, 0x57,
	0xb5, 0x2b, 0x37, 0x27, 0x6d, 0xe1, 0x7c, 0xa4, 0x46, 0xb3, 0x10, 0x32, 0x80, 0xf5, 0x74, 0x43,
	0x63, 0x41, 0x51, 0xd6, 0x4c, 0xcf, 0x66, 0x0e, 0x8a, 0xd4, 0xd2, 0x1b, 0x81, 0x41, 0xc4, 0x8d,
	0x09, 0xd2, 0x84, 0xb2, 0x40, 0x27, 0xd6, 0x11, 0xc0, 0x03, 0x89, 0x97, 0x52, 0xb7, 0xf7, 0xd7,
	0xce, 0x61, 0xe4, 0x6c, 0xee, 0x9e, 0x8d, 0x6b, 0xd3, 0xeb, 0x70, 0xf2, 0x05, 0x2c, 0xf6, 0xb9,
	0x1f, 0xf7, 0x50, 0x98, 0x6b, 0xd3, 0xdf, 0x97, 0x97, 0x5a, 0x85, 0x0e, 0x55, 0xc9, 0x01, 0x2c,
	0x27, 0x9f, 0x2f, 0x54, 0x68, 0x08, 0x93, 0x68, 0xe8, 0xbd, 0xe9, 0x50, 0xad, 0x47, 0xc7, 0x40,
	0xa4, 0x01, 0x45, 0xde, 0xc7, 0xc8, 0x57, 0x65, 0xac, 0xab, 0x09, 0x1e, 0x4d, 0x3f, 0xbc, 0x3d,
	0x71, 0xda, 0x52, 0xd5, 0xe3, 0x69, 0x82, 0xa0, 0x23, 0x68, 0xe5, 0x2b, 0x58, 0xbb, 0xf1, 0x54,
	0xcc, 0xf2, 0x68, 0x57, 0xf6, 0x61, 0x7d, 0xc2, 0xc5, 0x9c, 0x89, 0xa2, 0x01, 0x77, 0xa7, 0xb8,
	0x71, 0xa6, 0xf4, 0xf1, 0xc7, 0x1c, 0x18, 0xd7, 0x2d, 0x25, 0xf7, 0xa0, 0xc4, 0x42, 0xcf, 0x1e,
	0x6f, 0x36, 0x81, 0x85, 0x5e, 0xda, 0xa9, 0xa9, 0xcc, 0x7c, 0xe1, 0x05, 0x6e, 0x4a, 0xa7, 0xbf,
	0x27, 0x66, 0xeb, 0x17, 0xb0, 0x18, 0x32, 0xe9, 0x74, 0x51, 0xa4, 0xf9, 0xfa, 0xc9, 0xad, 0x8f,
	0xdb, 0x52, 0x95, 0x8e, 0xae, 0x19, 0xe8, 0x90, 0xa3, 0xf2, 0x6b, 0x58, 0x1a, 0x49, 0xd5, 0x7a,
	0xba, 0x3a, 0x4a, 0x76, 0xa7, 0xbf, 0x55, 0xdb, 0x95, 0x6d, 0x40, 0x6f, 0x9b, 0xc6, 0x13, 0x50,
	0xb5, 0x0c, 0x2b, 0x63, 0xf2, 0xaa, 0x09, 0xef, 0x4f, 0xfe, 0xfb, 0xa3, 0xfa, 0x3e, 0x6c, 0xa4,
	0xaa, 0xa7, 0x51, 0x32, 0xa7, 0x2b, 0x9b, 0xea, 0x06, 0x90, 0x9b, 0xf5, 0x4e, 0xfd, 0xf1, 0xdf,
	0x5f, 0x6d, 0xde, 0xf9, 0xe7, 0xab, 0xcd, 0x3b, 0xff, 0x7a, 0xb5, 0x79, 0xe7, 0x57, 0x9b, 0xc9,
	0xa6, 0xd2, 0xbf, 0x17, 0x6f, 0xfc, 0x73, 0xda, 0x5a, 0xd0, 0x55, 0xdc, 0x93, 0xff, 0x06, 0x00,
	0x00, 0xff, 0xff, 0x01, 0x8d, 0x3a, 0x8f, 0x55, 0x15, 0x00, 0x00,
}
